/* 투어리스트 일본 홀맵 DB — 각 구장 공식 사이트 원문 (출처 표기)
   ⚠️ 생성물입니다. 직접 고치지 마세요 — tools/jp/build_holeimgdb_jp.py 가 다시 씁니다.
   ⚠️ 거리 단위는 야드(y)입니다. 미터가 아닙니다. */
const HOLEIMG_DB_JP = {
  "キャッスルヒル カントリークラブ": {
    source: "アコーディア・ゴルフ 公式サイト",
    sourceUrl: "https://reserve.accordiagolf.com/golfCourse/aichi/castlehill/layout",
    unit: "yd",
    courses: [
      { name: "OUT", holes: [
        { no: 1, par: 4, img: "holeimg/jp_aichi_castlehill/OUT1.jpg", hdcp: 13, tees: [{ name: "Blue", y: 361 }, { name: "White", y: 340 }, { name: "Green", y: 311 }, { name: "Red", y: 280 }] },
        { no: 2, par: 5, img: "holeimg/jp_aichi_castlehill/OUT2.jpg", hdcp: 17, tees: [{ name: "Blue", y: 528 }, { name: "White", y: 486 }, { name: "Green", y: 462 }, { name: "Red", y: 353 }] },
        { no: 3, par: 3, img: "holeimg/jp_aichi_castlehill/OUT3.jpg", hdcp: 1, tees: [{ name: "Blue", y: 163 }, { name: "White", y: 140 }, { name: "Green", y: 119 }, { name: "Red", y: 119 }] },
        { no: 4, par: 4, img: "holeimg/jp_aichi_castlehill/OUT4.jpg", hdcp: 5, tees: [{ name: "Blue", y: 388 }, { name: "White", y: 360 }, { name: "Green", y: 323 }, { name: "Red", y: 293 }] },
        { no: 5, par: 5, img: "holeimg/jp_aichi_castlehill/OUT5.jpg", hdcp: 11, tees: [{ name: "Blue", y: 500 }, { name: "White", y: 458 }, { name: "Green", y: 420 }, { name: "Red", y: 328 }] },
        { no: 6, par: 3, img: "holeimg/jp_aichi_castlehill/OUT6.jpg", hdcp: 7, tees: [{ name: "Blue", y: 178 }, { name: "White", y: 151 }, { name: "Green", y: 110 }, { name: "Red", y: 110 }] },
        { no: 7, par: 4, img: "holeimg/jp_aichi_castlehill/OUT7.jpg", hdcp: 3, tees: [{ name: "Blue", y: 362 }, { name: "White", y: 342 }, { name: "Green", y: 316 }, { name: "Red", y: 224 }] },
        { no: 8, par: 4, img: "holeimg/jp_aichi_castlehill/OUT8.jpg", hdcp: 9, tees: [{ name: "Blue", y: 400 }, { name: "White", y: 378 }, { name: "Green", y: 334 }, { name: "Red", y: 294 }] },
        { no: 9, par: 4, img: "holeimg/jp_aichi_castlehill/OUT9.jpg", hdcp: 15, tees: [{ name: "Blue", y: 350 }, { name: "White", y: 329 }, { name: "Green", y: 296 }, { name: "Red", y: 215 }] },
      ]},
      { name: "IN", holes: [
        { no: 10, par: 4, img: "holeimg/jp_aichi_castlehill/IN10.jpg", hdcp: 18, tees: [{ name: "Blue", y: 312 }, { name: "White", y: 288 }, { name: "Green", y: 273 }, { name: "Red", y: 244 }] },
        { no: 11, par: 3, img: "holeimg/jp_aichi_castlehill/IN11.jpg", hdcp: 4, tees: [{ name: "Blue", y: 173 }, { name: "White", y: 152 }, { name: "Green", y: 130 }, { name: "Red", y: 104 }] },
        { no: 12, par: 4, img: "holeimg/jp_aichi_castlehill/IN12.jpg", hdcp: 8, tees: [{ name: "Blue", y: 399 }, { name: "White", y: 373 }, { name: "Green", y: 342 }, { name: "Red", y: 315 }] },
        { no: 13, par: 5, img: "holeimg/jp_aichi_castlehill/IN13.jpg", hdcp: 12, tees: [{ name: "Blue", y: 565 }, { name: "White", y: 545 }, { name: "Green", y: 482 }, { name: "Red", y: 392 }] },
        { no: 14, par: 3, img: "holeimg/jp_aichi_castlehill/IN14.jpg", hdcp: 2, tees: [{ name: "Blue", y: 179 }, { name: "White", y: 148 }, { name: "Green", y: 121 }, { name: "Red", y: 121 }] },
        { no: 15, par: 4, img: "holeimg/jp_aichi_castlehill/IN15.jpg", hdcp: 10, tees: [{ name: "Blue", y: 324 }, { name: "White", y: 306 }, { name: "Green", y: 270 }, { name: "Red", y: 200 }] },
        { no: 16, par: 4, img: "holeimg/jp_aichi_castlehill/IN16.jpg", hdcp: 16, tees: [{ name: "Blue", y: 360 }, { name: "White", y: 337 }, { name: "Green", y: 274 }, { name: "Red", y: 220 }] },
        { no: 17, par: 5, img: "holeimg/jp_aichi_castlehill/IN17.jpg", hdcp: 14, tees: [{ name: "Blue", y: 528 }, { name: "White", y: 484 }, { name: "Green", y: 450 }, { name: "Red", y: 419 }] },
        { no: 18, par: 4, img: "holeimg/jp_aichi_castlehill/IN18.jpg", hdcp: 6, tees: [{ name: "Blue", y: 416 }, { name: "White", y: 394 }, { name: "Green", y: 349 }, { name: "Red", y: 240 }] },
      ]},
    ],
  },
  "アクアラインゴルフクラブ": {
    source: "アコーディア・ゴルフ 公式サイト",
    sourceUrl: "https://reserve.accordiagolf.com/golfCourse/chiba/aqualine/layout",
    unit: "yd",
    courses: [
      { name: "OUT", holes: [
        { no: 1, par: 5, img: "holeimg/jp_chiba_aqualine/OUT1.jpg", hdcp: 9, tees: [{ name: "Blue", y: 525 }, { name: "White", y: 495 }, { name: "Green", y: 417 }, { name: "Red", y: 304 }] },
        { no: 2, par: 3, img: "holeimg/jp_chiba_aqualine/OUT2.jpg", hdcp: 17, tees: [{ name: "Blue", y: 119 }, { name: "White", y: 110 }, { name: "Green", y: 101 }, { name: "Red", y: 101 }] },
        { no: 3, par: 4, img: "holeimg/jp_chiba_aqualine/OUT3.jpg", hdcp: 5, tees: [{ name: "Blue", y: 365 }, { name: "White", y: 325 }, { name: "Green", y: 250 }, { name: "Red", y: 250 }] },
        { no: 4, par: 4, img: "holeimg/jp_chiba_aqualine/OUT4.jpg", hdcp: 15, tees: [{ name: "Blue", y: 312 }, { name: "White", y: 312 }, { name: "Green", y: 282 }, { name: "Red", y: 282 }] },
        { no: 5, par: 4, img: "holeimg/jp_chiba_aqualine/OUT5.jpg", hdcp: 7, tees: [{ name: "Blue", y: 407 }, { name: "White", y: 375 }, { name: "Green", y: 302 }, { name: "Red", y: 293 }] },
        { no: 6, par: 5, img: "holeimg/jp_chiba_aqualine/OUT6.jpg", hdcp: 1, tees: [{ name: "Blue", y: 605 }, { name: "White", y: 486 }, { name: "Green", y: 331 }, { name: "Red", y: 331 }] },
        { no: 7, par: 4, img: "holeimg/jp_chiba_aqualine/OUT7.jpg", hdcp: 13, tees: [{ name: "Blue", y: 342 }, { name: "White", y: 315 }, { name: "Green", y: 294 }, { name: "Red", y: 252 }] },
        { no: 8, par: 3, img: "holeimg/jp_chiba_aqualine/OUT8.jpg", hdcp: 11, tees: [{ name: "Blue", y: 170 }, { name: "White", y: 146 }, { name: "Green", y: 127 }, { name: "Red", y: 115 }] },
        { no: 9, par: 4, img: "holeimg/jp_chiba_aqualine/OUT9.jpg", hdcp: 3, tees: [{ name: "Blue", y: 435 }, { name: "White", y: 405 }, { name: "Green", y: 320 }, { name: "Red", y: 243 }] },
      ]},
      { name: "IN", holes: [
        { no: 10, par: 5, img: "holeimg/jp_chiba_aqualine/IN10.jpg", hdcp: 2, tees: [{ name: "Blue", y: 581 }, { name: "White", y: 540 }, { name: "Green", y: 481 }, { name: "Red", y: 345 }] },
        { no: 11, par: 3, img: "holeimg/jp_chiba_aqualine/IN11.jpg", hdcp: 8, tees: [{ name: "Blue", y: 185 }, { name: "White", y: 139 }, { name: "Green", y: 124 }, { name: "Red", y: 124 }] },
        { no: 12, par: 4, img: "holeimg/jp_chiba_aqualine/IN12.jpg", hdcp: 12, tees: [{ name: "Blue", y: 367 }, { name: "White", y: 367 }, { name: "Green", y: 234 }, { name: "Red", y: 234 }] },
        { no: 13, par: 5, img: "holeimg/jp_chiba_aqualine/IN13.jpg", hdcp: 10, tees: [{ name: "Blue", y: 540 }, { name: "White", y: 515 }, { name: "Green", y: 391 }, { name: "Red", y: 391 }] },
        { no: 14, par: 4, img: "holeimg/jp_chiba_aqualine/IN14.jpg", hdcp: 18, tees: [{ name: "Blue", y: 383 }, { name: "White", y: 360 }, { name: "Green", y: 302 }, { name: "Red", y: 252 }] },
        { no: 15, par: 4, img: "holeimg/jp_chiba_aqualine/IN15.jpg", hdcp: 6, tees: [{ name: "Blue", y: 395 }, { name: "White", y: 379 }, { name: "Green", y: 278 }, { name: "Red", y: 278 }] },
        { no: 16, par: 3, img: "holeimg/jp_chiba_aqualine/IN16.jpg", hdcp: 16, tees: [{ name: "Blue", y: 155 }, { name: "White", y: 155 }, { name: "Green", y: 130 }, { name: "Red", y: 98 }] },
        { no: 17, par: 4, img: "holeimg/jp_chiba_aqualine/IN17.jpg", hdcp: 14, tees: [{ name: "Blue", y: 385 }, { name: "White", y: 367 }, { name: "Green", y: 275 }, { name: "Red", y: 230 }] },
        { no: 18, par: 4, img: "holeimg/jp_chiba_aqualine/IN18.jpg", hdcp: 4, tees: [{ name: "Blue", y: 448 }, { name: "White", y: 390 }, { name: "Green", y: 342 }, { name: "Red", y: 250 }] },
      ]},
    ],
  },
  "土浦カントリー倶楽部": {
    source: "アコーディア・ゴルフ 公式サイト",
    sourceUrl: "https://reserve.accordiagolf.com/golfCourse/ibaraki/tsuchiura/layout",
    unit: "yd",
    green: "A",
    greens: 2,
    courses: [
      { name: "西", holes: [
        { no: 1, par: 4, img: "holeimg/jp_ibaraki_tsuchiura/西1.jpg", hdcp: 1, tees: [{ name: "Blue", y: 450 }, { name: "White", y: 435 }, { name: "Green", y: 435 }, { name: "Red", y: 332 }] },
        { no: 2, par: 4, img: "holeimg/jp_ibaraki_tsuchiura/西2.jpg", hdcp: 4, tees: [{ name: "Blue", y: 415 }, { name: "White", y: 395 }, { name: "Green", y: 395 }, { name: "Red", y: 340 }] },
        { no: 3, par: 5, img: "holeimg/jp_ibaraki_tsuchiura/西3.jpg", hdcp: 9, tees: [{ name: "Blue", y: 520 }, { name: "White", y: 490 }, { name: "Green", y: 470 }, { name: "Red", y: 337 }] },
        { no: 4, par: 3, img: "holeimg/jp_ibaraki_tsuchiura/西4.jpg", hdcp: 8, tees: [{ name: "Blue", y: 150 }, { name: "White", y: 141 }, { name: "Green", y: 135 }, { name: "Red", y: 97 }] },
        { no: 5, par: 4, img: "holeimg/jp_ibaraki_tsuchiura/西5.jpg", hdcp: 3, tees: [{ name: "Blue", y: 340 }, { name: "White", y: 325 }, { name: "Green", y: 325 }, { name: "Red", y: 320 }] },
        { no: 6, par: 3, img: "holeimg/jp_ibaraki_tsuchiura/西6.jpg", hdcp: 6, tees: [{ name: "Blue", y: 171 }, { name: "White", y: 158 }, { name: "Green", y: 146 }, { name: "Red", y: 132 }] },
        { no: 7, par: 4, img: "holeimg/jp_ibaraki_tsuchiura/西7.jpg", hdcp: 2, tees: [{ name: "Blue", y: 380 }, { name: "White", y: 355 }, { name: "Green", y: 355 }, { name: "Red", y: 300 }] },
        { no: 8, par: 4, img: "holeimg/jp_ibaraki_tsuchiura/西8.jpg", hdcp: 7, tees: [{ name: "Blue", y: 380 }, { name: "White", y: 350 }, { name: "Green", y: 326 }, { name: "Red", y: 223 }] },
        { no: 9, par: 5, img: "holeimg/jp_ibaraki_tsuchiura/西9.jpg", hdcp: 5, tees: [{ name: "Blue", y: 525 }, { name: "White", y: 495 }, { name: "Green", y: 495 }, { name: "Red", y: 387 }] },
      ]},
      { name: "南", holes: [
        { no: 1, par: 4, img: "holeimg/jp_ibaraki_tsuchiura/南1.jpg", hdcp: 5, tees: [{ name: "Blue", y: 360 }, { name: "White", y: 340 }, { name: "Green", y: 340 }, { name: "Red", y: 313 }] },
        { no: 2, par: 4, img: "holeimg/jp_ibaraki_tsuchiura/南2.jpg", hdcp: 3, tees: [{ name: "Blue", y: 455 }, { name: "White", y: 430 }, { name: "Green", y: 420 }, { name: "Red", y: 333 }] },
        { no: 3, par: 5, img: "holeimg/jp_ibaraki_tsuchiura/南3.jpg", hdcp: 1, tees: [{ name: "Blue", y: 545 }, { name: "White", y: 490 }, { name: "Green", y: 490 }, { name: "Red", y: 359 }] },
        { no: 4, par: 3, img: "holeimg/jp_ibaraki_tsuchiura/南4.jpg", hdcp: 8, tees: [{ name: "Blue", y: 150 }, { name: "White", y: 140 }, { name: "Green", y: 140 }, { name: "Red", y: 130 }] },
        { no: 5, par: 4, img: "holeimg/jp_ibaraki_tsuchiura/南5.jpg", hdcp: 4, tees: [{ name: "Blue", y: 390 }, { name: "White", y: 370 }, { name: "Green", y: 315 }, { name: "Red", y: 315 }] },
        { no: 6, par: 4, img: "holeimg/jp_ibaraki_tsuchiura/南6.jpg", hdcp: 7, tees: [{ name: "Blue", y: 370 }, { name: "White", y: 355 }, { name: "Green", y: 355 }, { name: "Red", y: 234 }] },
        { no: 7, par: 5, img: "holeimg/jp_ibaraki_tsuchiura/南7.jpg", hdcp: 2, tees: [{ name: "Blue", y: 560 }, { name: "White", y: 535 }, { name: "Green", y: 535 }, { name: "Red", y: 418 }] },
        { no: 8, par: 3, img: "holeimg/jp_ibaraki_tsuchiura/南8.jpg", hdcp: 9, tees: [{ name: "Blue", y: 150 }, { name: "White", y: 144 }, { name: "Green", y: 133 }, { name: "Red", y: 82 }] },
        { no: 9, par: 4, img: "holeimg/jp_ibaraki_tsuchiura/南9.jpg", hdcp: 6, tees: [{ name: "Blue", y: 445 }, { name: "White", y: 425 }, { name: "Green", y: 385 }, { name: "Red", y: 285 }] },
      ]},
      { name: "東", holes: [
        { no: 1, par: 5, img: "holeimg/jp_ibaraki_tsuchiura/東1.jpg", hdcp: 5, tees: [{ name: "Blue", y: 520 }, { name: "White", y: 505 }, { name: "Green", y: 505 }, { name: "Red", y: 410 }] },
        { no: 2, par: 4, img: "holeimg/jp_ibaraki_tsuchiura/東2.jpg", hdcp: 2, tees: [{ name: "Blue", y: 395 }, { name: "White", y: 380 }, { name: "Green", y: 360 }, { name: "Red", y: 291 }] },
        { no: 3, par: 3, img: "holeimg/jp_ibaraki_tsuchiura/東3.jpg", hdcp: 9, tees: [{ name: "Blue", y: 175 }, { name: "White", y: 155 }, { name: "Green", y: 155 }, { name: "Red", y: 138 }] },
        { no: 4, par: 4, img: "holeimg/jp_ibaraki_tsuchiura/東4.jpg", hdcp: 1, tees: [{ name: "Blue", y: 450 }, { name: "White", y: 420 }, { name: "Green", y: 420 }, { name: "Red", y: 357 }] },
        { no: 5, par: 3, img: "holeimg/jp_ibaraki_tsuchiura/東5.jpg", hdcp: 6, tees: [{ name: "Blue", y: 205 }, { name: "White", y: 170 }, { name: "Green", y: 123 }, { name: "Red", y: 94 }] },
        { no: 6, par: 5, img: "holeimg/jp_ibaraki_tsuchiura/東6.jpg", hdcp: 3, tees: [{ name: "Blue", y: 530 }, { name: "White", y: 505 }, { name: "Green", y: 505 }, { name: "Red", y: 456 }] },
        { no: 7, par: 4, img: "holeimg/jp_ibaraki_tsuchiura/東7.jpg", hdcp: 8, tees: [{ name: "Blue", y: 345 }, { name: "White", y: 335 }, { name: "Green", y: 335 }, { name: "Red", y: 308 }] },
        { no: 8, par: 4, img: "holeimg/jp_ibaraki_tsuchiura/東8.jpg", hdcp: 4, tees: [{ name: "Blue", y: 395 }, { name: "White", y: 370 }, { name: "Green", y: 370 }, { name: "Red", y: 328 }] },
        { no: 9, par: 4, img: "holeimg/jp_ibaraki_tsuchiura/東9.jpg", hdcp: 7, tees: [{ name: "Blue", y: 385 }, { name: "White", y: 365 }, { name: "Green", y: 365 }, { name: "Red", y: 285 }] },
      ]},
    ],
  },
};
